### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by SamuelPelletierEvraire** [SamuelPelletierEvraire/ImageStitchingPython-main#1]
So this is a test for image stitching but i have a problem with the subnet method (I'm obligated to stop the request or else it go non stop and it is looping whit no end)

**Comment by MaxenceGui** [comment]
Hi Samuel, I few comments on Python's convention:

- Usually in Python, we don't divide functions into separate files. We tend to regroup in module-related functionality. For example, everything that would be camera-related would be written in a camera module, and so on. It will avoid the long import list that you have set up in `app.py`.

- Also use the if __name__ == "__main__"" [syntaxe](https://realpython.com/if-name-main-python/#:~:text=At%20its%20core%2C%20the%20idiom%20is%20a%20conditional,is%20False%2C%20then%20Python%20skips%20the%20indented%20code.) Follow the link to know more about this feature.

- When you use an external library (like cv2) you can set up a requirements.txt listing all of them. Use the `pip freeze > requirements.txt` command to automatically create the file. Afterward, when someone else uses your code they can use `pip install -r requirements.txt` to recreate your environment.

I hope those tips are useful, I have tried to run your code, but I'm having trouble installing cv2. If you can provide the requirements.txt, it will help a lot 😃 . Also, can you be a little more specific on the trouble you have? What line of code should we looking at?

**Comment by SamuelPelletierEvraire** [comment]
Issue as been corrected and now the code work well
